//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignTable
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using ProtoBuf;
    
    
    [ProtoContract()]
    public class AtlasDataInfo
    {
        
        [ProtoMember(1)]
        public int AtlasType;
        
        [ProtoMember(2)]
        public string Path;
        
        public AtlasDataInfo()
        {
        }
        
        public AtlasDataInfo(int AtlasType, string Path)
        {
			this.AtlasType = AtlasType;
			this.Path = Path;
        }
    }
    
    [ProtoContract()]
    public class AtlasDataInfos
    {
        
        [ProtoMember(1)]
        public List<AtlasDataInfo> dataInfo = new List<AtlasDataInfo>();
        
        public Dictionary<System.Int32, AtlasDataInfo> datas = new Dictionary<System.Int32, AtlasDataInfo>();
        
        public bool Insert(int AtlasType, string Path)
        {
			System.Int32 key = AtlasType;
			if (datas.ContainsKey(key))
				return false;
			AtlasDataInfo newInfo = new AtlasDataInfo(AtlasType, Path);
			dataInfo.Add(newInfo);
			datas.Add(key, newInfo);
			return true;
        }
        
        public void Initialize()
        {
			var newDatas = new Dictionary<System.Int32, AtlasDataInfo>();
			foreach (var data in dataInfo)
			{
				System.Int32 key = data.AtlasType;
				if (newDatas.ContainsKey(key))
					throw new InvalidOperationException("Duplicate primary key in table 'AtlasData': " + key);
				newDatas.Add(key, data);
			}
			datas = newDatas;
        }
        
        public AtlasDataInfo Get(int AtlasType)
        {
			AtlasDataInfo value = null;
			if (datas.TryGetValue(AtlasType, out value))
				return value;
			return null;
        }
    }
}
