//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignTable
{
    using System;
    using System.IO;
    using System.Linq;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;
    
    
    public class DataComparer : System.Collections.Generic.IEqualityComparer<ArraySegment<byte>>
    {
        
        public bool Equals(System.ArraySegment<byte> x, System.ArraySegment<byte> y)
        {
			return x.SequenceEqual(y);
        }
        
        public int GetHashCode(System.ArraySegment<byte> obj)
        {
			if (obj.Array == null) return 0;
			unchecked
			{
				int hash = (int)2166136261;
				for (int i = obj.Offset; i < obj.Offset + obj.Count; ++i)
					hash = (hash ^ obj.Array[i]) * 16777619;
				return hash;
			}
        }
    }
    
    public enum TableId
    {
        
        user_character = 1011,
        
        skill = 1013,
        
        buff = 1014,
        
        skill_effect = 1015,
        
        monster_master = 1016,
        
        monster_normal = 1017,
        
        monster_boss = 1018,
        
        monster_deploy = 1019,
        
        quest = 1020,
        
        passive = 1021,
        
        projectile = 1022,
        
        AtlasData = 1023,
        
        SceneData = 1024,
    }
    
    public class DataMgr
    {
        
        private delegate void LoadHandler(byte[] data);
        
        private delegate void ClearHandler();
        
        private Dictionary<int, DataMgr.LoadHandler> loadHandlerList = new Dictionary<int, LoadHandler>();
        
        private Dictionary<int, DataMgr.ClearHandler> clearHandlerList = new Dictionary<int, ClearHandler>();
        
        private bool isCallInit = false;
        
        private DataMessageSerializer serializer = new DataMessageSerializer();
        
        private user_characterInfos user_characterInfos;
        
        public user_characterInfos User_characterInfos => user_characterInfos;
        
        private skillInfos skillInfos;
        
        public skillInfos SkillInfos => skillInfos;
        
        private buffInfos buffInfos;
        
        public buffInfos BuffInfos => buffInfos;
        
        private skill_effectInfos skill_effectInfos;
        
        public skill_effectInfos Skill_effectInfos => skill_effectInfos;
        
        private monster_masterInfos monster_masterInfos;
        
        public monster_masterInfos Monster_masterInfos => monster_masterInfos;
        
        private monster_normalInfos monster_normalInfos;
        
        public monster_normalInfos Monster_normalInfos => monster_normalInfos;
        
        private monster_bossInfos monster_bossInfos;
        
        public monster_bossInfos Monster_bossInfos => monster_bossInfos;
        
        private monster_deployInfos monster_deployInfos;
        
        public monster_deployInfos Monster_deployInfos => monster_deployInfos;
        
        private questInfos questInfos;
        
        public questInfos QuestInfos => questInfos;
        
        private passiveInfos passiveInfos;
        
        public passiveInfos PassiveInfos => passiveInfos;
        
        private projectileInfos projectileInfos;
        
        public projectileInfos ProjectileInfos => projectileInfos;
        
        private AtlasDataInfos atlasDataInfos;
        
        public AtlasDataInfos AtlasDataInfos => atlasDataInfos;
        
        private SceneDataInfos sceneDataInfos;
        
        public SceneDataInfos SceneDataInfos => sceneDataInfos;
        
        public void Init()
        {
			if (isCallInit)
				return;
			RegisterLoadHandler();
			RegisterClearHandler();
			isCallInit = true;
        }
        
        public void LoadData(TableId dataType, byte[] data)
        {
			loadHandlerList[(int)dataType](data);
        }
        
        public void ClearData(TableId[] dataTypes)
        {
			foreach (int dataType in dataTypes)
			{
				clearHandlerList[dataType]();
			}
        }
        
        public void ClearData(TableId dataType)
        {
			clearHandlerList[(int)dataType]();
        }
        
        public void ClearDataAll()
        {
			foreach (DataMgr.ClearHandler clearHandler in clearHandlerList.Values)
			{
				clearHandler();
			}
        }
        
        private void RegisterLoadHandler()
        {
			loadHandlerList.Add(1011, new DataMgr.LoadHandler(Loaduser_characterInfos));
			loadHandlerList.Add(1013, new DataMgr.LoadHandler(LoadskillInfos));
			loadHandlerList.Add(1014, new DataMgr.LoadHandler(LoadbuffInfos));
			loadHandlerList.Add(1015, new DataMgr.LoadHandler(Loadskill_effectInfos));
			loadHandlerList.Add(1016, new DataMgr.LoadHandler(Loadmonster_masterInfos));
			loadHandlerList.Add(1017, new DataMgr.LoadHandler(Loadmonster_normalInfos));
			loadHandlerList.Add(1018, new DataMgr.LoadHandler(Loadmonster_bossInfos));
			loadHandlerList.Add(1019, new DataMgr.LoadHandler(Loadmonster_deployInfos));
			loadHandlerList.Add(1020, new DataMgr.LoadHandler(LoadquestInfos));
			loadHandlerList.Add(1021, new DataMgr.LoadHandler(LoadpassiveInfos));
			loadHandlerList.Add(1022, new DataMgr.LoadHandler(LoadprojectileInfos));
			loadHandlerList.Add(1023, new DataMgr.LoadHandler(LoadAtlasDataInfos));
			loadHandlerList.Add(1024, new DataMgr.LoadHandler(LoadSceneDataInfos));
        }
        
        private void RegisterClearHandler()
        {
			clearHandlerList.Add(1011, ClearDatauser_characterInfos);
			clearHandlerList.Add(1013, ClearDataskillInfos);
			clearHandlerList.Add(1014, ClearDatabuffInfos);
			clearHandlerList.Add(1015, ClearDataskill_effectInfos);
			clearHandlerList.Add(1016, ClearDatamonster_masterInfos);
			clearHandlerList.Add(1017, ClearDatamonster_normalInfos);
			clearHandlerList.Add(1018, ClearDatamonster_bossInfos);
			clearHandlerList.Add(1019, ClearDatamonster_deployInfos);
			clearHandlerList.Add(1020, ClearDataquestInfos);
			clearHandlerList.Add(1021, ClearDatapassiveInfos);
			clearHandlerList.Add(1022, ClearDataprojectileInfos);
			clearHandlerList.Add(1023, ClearDataAtlasDataInfos);
			clearHandlerList.Add(1024, ClearDataSceneDataInfos);
        }
        
        private void Loaduser_characterInfos(byte[] data)
        {
			user_characterInfos = serializer.Deserialize(1011, data) as user_characterInfos;
			if (user_characterInfos != null)
				user_characterInfos.Initialize();
        }
        
        private void LoadskillInfos(byte[] data)
        {
			skillInfos = serializer.Deserialize(1013, data) as skillInfos;
			if (skillInfos != null)
				skillInfos.Initialize();
        }
        
        private void LoadbuffInfos(byte[] data)
        {
			buffInfos = serializer.Deserialize(1014, data) as buffInfos;
			if (buffInfos != null)
				buffInfos.Initialize();
        }
        
        private void Loadskill_effectInfos(byte[] data)
        {
			skill_effectInfos = serializer.Deserialize(1015, data) as skill_effectInfos;
			if (skill_effectInfos != null)
				skill_effectInfos.Initialize();
        }
        
        private void Loadmonster_masterInfos(byte[] data)
        {
			monster_masterInfos = serializer.Deserialize(1016, data) as monster_masterInfos;
			if (monster_masterInfos != null)
				monster_masterInfos.Initialize();
        }
        
        private void Loadmonster_normalInfos(byte[] data)
        {
			monster_normalInfos = serializer.Deserialize(1017, data) as monster_normalInfos;
			if (monster_normalInfos != null)
				monster_normalInfos.Initialize();
        }
        
        private void Loadmonster_bossInfos(byte[] data)
        {
			monster_bossInfos = serializer.Deserialize(1018, data) as monster_bossInfos;
			if (monster_bossInfos != null)
				monster_bossInfos.Initialize();
        }
        
        private void Loadmonster_deployInfos(byte[] data)
        {
			monster_deployInfos = serializer.Deserialize(1019, data) as monster_deployInfos;
			if (monster_deployInfos != null)
				monster_deployInfos.Initialize();
        }
        
        private void LoadquestInfos(byte[] data)
        {
			questInfos = serializer.Deserialize(1020, data) as questInfos;
			if (questInfos != null)
				questInfos.Initialize();
        }
        
        private void LoadpassiveInfos(byte[] data)
        {
			passiveInfos = serializer.Deserialize(1021, data) as passiveInfos;
			if (passiveInfos != null)
				passiveInfos.Initialize();
        }
        
        private void LoadprojectileInfos(byte[] data)
        {
			projectileInfos = serializer.Deserialize(1022, data) as projectileInfos;
			if (projectileInfos != null)
				projectileInfos.Initialize();
        }
        
        private void LoadAtlasDataInfos(byte[] data)
        {
			atlasDataInfos = serializer.Deserialize(1023, data) as AtlasDataInfos;
			if (atlasDataInfos != null)
				atlasDataInfos.Initialize();
        }
        
        private void LoadSceneDataInfos(byte[] data)
        {
			sceneDataInfos = serializer.Deserialize(1024, data) as SceneDataInfos;
			if (sceneDataInfos != null)
				sceneDataInfos.Initialize();
        }
        
        private void ClearDatauser_characterInfos()
        {
			if (user_characterInfos != null)
				user_characterInfos = null;
        }
        
        private void ClearDataskillInfos()
        {
			if (skillInfos != null)
				skillInfos = null;
        }
        
        private void ClearDatabuffInfos()
        {
			if (buffInfos != null)
				buffInfos = null;
        }
        
        private void ClearDataskill_effectInfos()
        {
			if (skill_effectInfos != null)
				skill_effectInfos = null;
        }
        
        private void ClearDatamonster_masterInfos()
        {
			if (monster_masterInfos != null)
				monster_masterInfos = null;
        }
        
        private void ClearDatamonster_normalInfos()
        {
			if (monster_normalInfos != null)
				monster_normalInfos = null;
        }
        
        private void ClearDatamonster_bossInfos()
        {
			if (monster_bossInfos != null)
				monster_bossInfos = null;
        }
        
        private void ClearDatamonster_deployInfos()
        {
			if (monster_deployInfos != null)
				monster_deployInfos = null;
        }
        
        private void ClearDataquestInfos()
        {
			if (questInfos != null)
				questInfos = null;
        }
        
        private void ClearDatapassiveInfos()
        {
			if (passiveInfos != null)
				passiveInfos = null;
        }
        
        private void ClearDataprojectileInfos()
        {
			if (projectileInfos != null)
				projectileInfos = null;
        }
        
        private void ClearDataAtlasDataInfos()
        {
			if (atlasDataInfos != null)
				atlasDataInfos = null;
        }
        
        private void ClearDataSceneDataInfos()
        {
			if (sceneDataInfos != null)
				sceneDataInfos = null;
        }
        
        public void SetUpRef()
        {
			if (skillInfos != null && buffInfos != null)
				skillInfos.SetupRef_skill_buffId(buffInfos);
			if (skillInfos != null && skill_effectInfos != null)
				skillInfos.SetupRef_effect_Id(skill_effectInfos);
			if (skillInfos != null && projectileInfos != null)
				skillInfos.SetupRef_projectile_Id(projectileInfos);
        }
    }
}
