//------------------------------------------------------------------------------
// <auto-generated>
//     �� �ڵ�� ������ ����Ͽ� �����Ǿ����ϴ�.
//     ��Ÿ�� ����:4.0.30319.42000
//
//     ���� ������ �����ϸ� �߸��� ������ �߻��� �� ������, �ڵ带 �ٽ� �����ϸ�
//     �̷��� ���� ������ �սǵ˴ϴ�.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignTable
{
    using DesignTable;
    using ProtoBuf;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    
    
    public sealed class DataMessageSerializer
    {
        
        public byte[] Serialize(object tableInfos)
        {
		System.IO.MemoryStream stream = new System.IO.MemoryStream();
		Serializer.Serialize(stream, tableInfos);
		byte[] buffer = stream.ToArray();

		return buffer;
        }
        
        public object Deserialize(int tableId, byte[] buffer)
        {
		System.IO.MemoryStream stream = new System.IO.MemoryStream(buffer);
		switch (tableId)
		{
			case 1023:
				return ProtoBuf.Serializer.Deserialize<AtlasDataInfos>(stream);
			case 1014:
				return ProtoBuf.Serializer.Deserialize<buffInfos>(stream);
			case 1018:
				return ProtoBuf.Serializer.Deserialize<monster_bossInfos>(stream);
			case 1019:
				return ProtoBuf.Serializer.Deserialize<monster_deployInfos>(stream);
			case 1016:
				return ProtoBuf.Serializer.Deserialize<monster_masterInfos>(stream);
			case 1017:
				return ProtoBuf.Serializer.Deserialize<monster_normalInfos>(stream);
			case 1021:
				return ProtoBuf.Serializer.Deserialize<passiveInfos>(stream);
			case 1022:
				return ProtoBuf.Serializer.Deserialize<projectileInfos>(stream);
			case 1020:
				return ProtoBuf.Serializer.Deserialize<questInfos>(stream);
			case 1024:
				return ProtoBuf.Serializer.Deserialize<SceneDataInfos>(stream);
			case 1013:
				return ProtoBuf.Serializer.Deserialize<skillInfos>(stream);
			case 1015:
				return ProtoBuf.Serializer.Deserialize<skill_effectInfos>(stream);
			case 1011:
				return ProtoBuf.Serializer.Deserialize<user_characterInfos>(stream);
		}
		return null;
        }
    }
}
