//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignTable
{
    using DesignTable;
    using ProtoBuf;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    
    
    public sealed class DataMessageSerializer
    {
        
        public byte[] Serialize(object tableInfos)
        {
			using (System.IO.MemoryStream stream = new System.IO.MemoryStream())
			{
				Serializer.Serialize(stream, tableInfos);
				return stream.ToArray();
			}
        }
        
        public object Deserialize(int tableId, byte[] buffer)
        {
			using (System.IO.MemoryStream stream = new System.IO.MemoryStream(buffer))
			{
				switch (tableId)
				{
					case 1011:
						return ProtoBuf.Serializer.Deserialize<user_characterInfos>(stream);
					case 1013:
						return ProtoBuf.Serializer.Deserialize<skillInfos>(stream);
					case 1014:
						return ProtoBuf.Serializer.Deserialize<buffInfos>(stream);
					case 1015:
						return ProtoBuf.Serializer.Deserialize<skill_effectInfos>(stream);
					case 1016:
						return ProtoBuf.Serializer.Deserialize<monster_masterInfos>(stream);
					case 1017:
						return ProtoBuf.Serializer.Deserialize<monster_normalInfos>(stream);
					case 1018:
						return ProtoBuf.Serializer.Deserialize<monster_bossInfos>(stream);
					case 1019:
						return ProtoBuf.Serializer.Deserialize<monster_deployInfos>(stream);
					case 1020:
						return ProtoBuf.Serializer.Deserialize<questInfos>(stream);
					case 1021:
						return ProtoBuf.Serializer.Deserialize<passiveInfos>(stream);
					case 1022:
						return ProtoBuf.Serializer.Deserialize<projectileInfos>(stream);
					case 1023:
						return ProtoBuf.Serializer.Deserialize<AtlasDataInfos>(stream);
					case 1024:
						return ProtoBuf.Serializer.Deserialize<SceneDataInfos>(stream);
					default:
						throw new System.ArgumentOutOfRangeException("tableId", "알 수 없는 TableId: " + tableId);
				}
			}
        }
    }
}
