//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignTable
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using ProtoBuf;
    
    
    [ProtoContract()]
    public class monster_deployInfo
    {
        
        [ProtoMember(1)]
        public short mon_fieldType;
        
        [ProtoMember(2)]
        public short mon_id;
        
        [ProtoMember(3)]
        public short mon_type;
        
        public monster_deployInfo()
        {
        }
        
        public monster_deployInfo(short mon_fieldType, short mon_id, short mon_type)
        {
			this.mon_fieldType = mon_fieldType;
			this.mon_id = mon_id;
			this.mon_type = mon_type;
        }
    }
    
    [ProtoContract()]
    public class monster_deployInfos
    {
        
        [ProtoMember(1)]
        public List<monster_deployInfo> dataInfo = new List<monster_deployInfo>();
        
        public Dictionary<System.ValueTuple<System.Int16, System.Int16>, monster_deployInfo> datas = new Dictionary<System.ValueTuple<System.Int16, System.Int16>, monster_deployInfo>();
        
        public Dictionary<System.Int16, List<monster_deployInfo>> listData = new Dictionary<System.Int16, List<monster_deployInfo>>();
        
        public bool Insert(short mon_fieldType, short mon_id, short mon_type)
        {
			System.ValueTuple<System.Int16, System.Int16> key = new System.ValueTuple<System.Int16, System.Int16>(mon_fieldType, mon_id);
			if (datas.ContainsKey(key))
				return false;
			monster_deployInfo newInfo = new monster_deployInfo(mon_fieldType, mon_id, mon_type);
			dataInfo.Add(newInfo);
			datas.Add(key, newInfo);
			System.Int16 listKey = mon_fieldType;
			List<monster_deployInfo> listValues = null;
			if (!listData.TryGetValue(listKey, out listValues))
			{
				listValues = new List<monster_deployInfo>();
				listData.Add(listKey, listValues);
			}
			listValues.Add(newInfo);
			return true;
        }
        
        public void Initialize()
        {
			var newDatas = new Dictionary<System.ValueTuple<System.Int16, System.Int16>, monster_deployInfo>();
			var newListData = new Dictionary<System.Int16, List<monster_deployInfo>>();
			foreach (var data in dataInfo)
			{
				System.ValueTuple<System.Int16, System.Int16> key = new System.ValueTuple<System.Int16, System.Int16>(data.mon_fieldType, data.mon_id);
				if (newDatas.ContainsKey(key))
					throw new InvalidOperationException("Duplicate primary key in table 'monster_deploy': " + key);
				newDatas.Add(key, data);
				System.Int16 listKey = data.mon_fieldType;
				List<monster_deployInfo> listValues = null;
				if (!newListData.TryGetValue(listKey, out listValues))
				{
					listValues = new List<monster_deployInfo>();
					newListData.Add(listKey, listValues);
				}
				listValues.Add(data);
			}
			datas = newDatas;
			listData = newListData;
        }
        
        public monster_deployInfo Get(short mon_fieldType, short mon_id)
        {
			monster_deployInfo value = null;
			if (datas.TryGetValue(new System.ValueTuple<System.Int16, System.Int16>(mon_fieldType, mon_id), out value))
				return value;
			return null;
        }
        
        public List<monster_deployInfo> GetListById(short mon_fieldType)
        {
			List<monster_deployInfo> value = null;
			if (listData.TryGetValue(mon_fieldType, out value))
				return value;
			return null;
        }
    }
}
