//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignTable
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using ProtoBuf;
    
    
    [ProtoContract()]
    public class monster_bossInfo
    {
        
        [ProtoMember(1)]
        public short mon_id;
        
        [ProtoMember(2)]
        public int mon_pathId;
        
        [ProtoMember(3)]
        public sbyte mon_type;
        
        [ProtoMember(4)]
        public short mon_spawnId;
        
        [ProtoMember(5)]
        public short mon_spawnTime;
        
        [ProtoMember(6)]
        public sbyte mon_spawnDayNight;
        
        public monster_bossInfo()
        {
        }
        
        public monster_bossInfo(short mon_id, int mon_pathId, sbyte mon_type, short mon_spawnId, short mon_spawnTime, sbyte mon_spawnDayNight)
        {
			this.mon_id = mon_id;
			this.mon_pathId = mon_pathId;
			this.mon_type = mon_type;
			this.mon_spawnId = mon_spawnId;
			this.mon_spawnTime = mon_spawnTime;
			this.mon_spawnDayNight = mon_spawnDayNight;
        }
    }
    
    [ProtoContract()]
    public class monster_bossInfos
    {
        
        [ProtoMember(1)]
        public List<monster_bossInfo> dataInfo = new List<monster_bossInfo>();
        
        public Dictionary<System.Int16, monster_bossInfo> datas = new Dictionary<System.Int16, monster_bossInfo>();
        
        public bool Insert(short mon_id, int mon_pathId, sbyte mon_type, short mon_spawnId, short mon_spawnTime, sbyte mon_spawnDayNight)
        {
			System.Int16 key = mon_id;
			if (datas.ContainsKey(key))
				return false;
			monster_bossInfo newInfo = new monster_bossInfo(mon_id, mon_pathId, mon_type, mon_spawnId, mon_spawnTime, mon_spawnDayNight);
			dataInfo.Add(newInfo);
			datas.Add(key, newInfo);
			return true;
        }
        
        public void Initialize()
        {
			var newDatas = new Dictionary<System.Int16, monster_bossInfo>();
			foreach (var data in dataInfo)
			{
				System.Int16 key = data.mon_id;
				if (newDatas.ContainsKey(key))
					throw new InvalidOperationException("Duplicate primary key in table 'monster_boss': " + key);
				newDatas.Add(key, data);
			}
			datas = newDatas;
        }
        
        public monster_bossInfo Get(short mon_id)
        {
			monster_bossInfo value = null;
			if (datas.TryGetValue(mon_id, out value))
				return value;
			return null;
        }
    }
}
