//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignTable
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using ProtoBuf;
    
    
    [ProtoContract()]
    public class monster_masterInfo
    {
        
        [ProtoMember(1)]
        public short mon_id;
        
        [ProtoMember(2)]
        public string mon_name;
        
        [ProtoMember(3)]
        public short mon_atk;
        
        [ProtoMember(4)]
        public short mon_def;
        
        [ProtoMember(5)]
        public short mon_hp;
        
        [ProtoMember(6)]
        public short mon_speed;
        
        [ProtoMember(7)]
        public sbyte mon_type;
        
        [ProtoMember(8)]
        public short mon_searchAngle;
        
        [ProtoMember(9)]
        public short mon_searchRange;
        
        [ProtoMember(10)]
        public float mon_keppRange;
        
        [ProtoMember(11)]
        public string mon_prefab;
        
        public monster_masterInfo()
        {
        }
        
        public monster_masterInfo(short mon_id, string mon_name, short mon_atk, short mon_def, short mon_hp, short mon_speed, sbyte mon_type, short mon_searchAngle, short mon_searchRange, float mon_keppRange, string mon_prefab)
        {
			this.mon_id = mon_id;
			this.mon_name = mon_name;
			this.mon_atk = mon_atk;
			this.mon_def = mon_def;
			this.mon_hp = mon_hp;
			this.mon_speed = mon_speed;
			this.mon_type = mon_type;
			this.mon_searchAngle = mon_searchAngle;
			this.mon_searchRange = mon_searchRange;
			this.mon_keppRange = mon_keppRange;
			this.mon_prefab = mon_prefab;
        }
    }
    
    [ProtoContract()]
    public class monster_masterInfos
    {
        
        [ProtoMember(1)]
        public List<monster_masterInfo> dataInfo = new List<monster_masterInfo>();
        
        public Dictionary<System.Int16, monster_masterInfo> datas = new Dictionary<System.Int16, monster_masterInfo>();
        
        public bool Insert(short mon_id, string mon_name, short mon_atk, short mon_def, short mon_hp, short mon_speed, sbyte mon_type, short mon_searchAngle, short mon_searchRange, float mon_keppRange, string mon_prefab)
        {
			System.Int16 key = mon_id;
			if (datas.ContainsKey(key))
				return false;
			monster_masterInfo newInfo = new monster_masterInfo(mon_id, mon_name, mon_atk, mon_def, mon_hp, mon_speed, mon_type, mon_searchAngle, mon_searchRange, mon_keppRange, mon_prefab);
			dataInfo.Add(newInfo);
			datas.Add(key, newInfo);
			return true;
        }
        
        public void Initialize()
        {
			var newDatas = new Dictionary<System.Int16, monster_masterInfo>();
			foreach (var data in dataInfo)
			{
				System.Int16 key = data.mon_id;
				if (newDatas.ContainsKey(key))
					throw new InvalidOperationException("Duplicate primary key in table 'monster_master': " + key);
				newDatas.Add(key, data);
			}
			datas = newDatas;
        }
        
        public monster_masterInfo Get(short mon_id)
        {
			monster_masterInfo value = null;
			if (datas.TryGetValue(mon_id, out value))
				return value;
			return null;
        }
    }
}
