//------------------------------------------------------------------------------
// <auto-generated>
//     �� �ڵ�� ������ ����Ͽ� �����Ǿ����ϴ�.
//     ��Ÿ�� ����:4.0.30319.42000
//
//     ���� ������ �����ϸ� �߸��� ������ �߻��� �� ������, �ڵ带 �ٽ� �����ϸ�
//     �̷��� ���� ������ �սǵ˴ϴ�.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignTable
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using ProtoBuf;
    
    
    [ProtoContract()]
    public class monster_masterInfo
    {
        
        [ProtoMember(1)]
        public short mon_id;
        
        [ProtoMember(2)]
        public string mon_name;
        
        [ProtoMember(3)]
        public short mon_atk;
        
        [ProtoMember(4)]
        public short mon_def;
        
        [ProtoMember(5)]
        public short mon_hp;
        
        [ProtoMember(6)]
        public short mon_speed;
        
        [ProtoMember(7)]
        public sbyte mon_type;
        
        [ProtoMember(8)]
        public short mon_searchAngle;
        
        [ProtoMember(9)]
        public short mon_searchRange;
        
        [ProtoMember(10)]
        public float mon_keppRange;
        
        [ProtoMember(11)]
        public string mon_prefab;
        
        public monster_masterInfo()
        {
        }
        
        public monster_masterInfo(short mon_id, string mon_name, short mon_atk, short mon_def, short mon_hp, short mon_speed, sbyte mon_type, short mon_searchAngle, short mon_searchRange, float mon_keppRange, string mon_prefab)
        {
		this.mon_id = mon_id;
		this.mon_name = mon_name;
		this.mon_atk = mon_atk;
		this.mon_def = mon_def;
		this.mon_hp = mon_hp;
		this.mon_speed = mon_speed;
		this.mon_type = mon_type;
		this.mon_searchAngle = mon_searchAngle;
		this.mon_searchRange = mon_searchRange;
		this.mon_keppRange = mon_keppRange;
		this.mon_prefab = mon_prefab;
        }
    }
    
    [ProtoContract()]
    public class monster_masterInfos
    {
        
        [ProtoMember(1)]
        public List<monster_masterInfo> dataInfo = new List<monster_masterInfo>();
        
        public Dictionary<ArraySegment<byte>, monster_masterInfo> datas = new Dictionary<ArraySegment<byte>, monster_masterInfo>(new DataComparer());
        
        public bool Insert(short mon_id, string mon_name, short mon_atk, short mon_def, short mon_hp, short mon_speed, sbyte mon_type, short mon_searchAngle, short mon_searchRange, float mon_keppRange, string mon_prefab)
        {
		foreach (monster_masterInfo info in dataInfo)
		{
			if(info.mon_id == mon_id)
			{
				return false;
			}
		}
			dataInfo.Add(new monster_masterInfo(mon_id,mon_name,mon_atk,mon_def,mon_hp,mon_speed,mon_type,mon_searchAngle,mon_searchRange,mon_keppRange,mon_prefab));
			return true;
        }
        
        public void Initialize()
        {
		foreach (var data in dataInfo)
		{
			ArraySegment<byte> bytes = GetIdRule(data.mon_id);
			if (datas.ContainsKey(bytes))
				continue;
			datas.Add(bytes, data);
		}
        }
        
        public monster_masterInfo Get(short mon_id)
        {
		monster_masterInfo value = null;


		if (datas.TryGetValue(GetIdRule(mon_id), out value))
			return value;
		return null;
        }
        
        public System.ArraySegment<byte> GetIdRule(short mon_id)
        {
		ushort total = 0;
		ushort count = 0;
		total += sizeof(short);


		if( total == 0 )
			return default(System.ArraySegment<byte>);


		byte[] bytes = new byte[total];
		Array.Copy(BitConverter.GetBytes(mon_id), 0, bytes, count, sizeof(short));
		count += sizeof(short);


		 return new System.ArraySegment<byte>(bytes);
        }
    }
}
