//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignTable
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using ProtoBuf;
    
    
    [ProtoContract()]
    public class passiveInfo
    {
        
        [ProtoMember(1)]
        public short passive_Id;
        
        [ProtoMember(2)]
        public short status_Type;
        
        [ProtoMember(3)]
        public short status_Arg;
        
        [ProtoMember(4)]
        public string passive_name;
        
        [ProtoMember(5)]
        public string image_Res;
        
        public passiveInfo()
        {
        }
        
        public passiveInfo(short passive_Id, short status_Type, short status_Arg, string passive_name, string image_Res)
        {
			this.passive_Id = passive_Id;
			this.status_Type = status_Type;
			this.status_Arg = status_Arg;
			this.passive_name = passive_name;
			this.image_Res = image_Res;
        }
    }
    
    [ProtoContract()]
    public class passiveInfos
    {
        
        [ProtoMember(1)]
        public List<passiveInfo> dataInfo = new List<passiveInfo>();
        
        public Dictionary<System.Int16, passiveInfo> datas = new Dictionary<System.Int16, passiveInfo>();
        
        public bool Insert(short passive_Id, short status_Type, short status_Arg, string passive_name, string image_Res)
        {
			System.Int16 key = passive_Id;
			if (datas.ContainsKey(key))
				return false;
			passiveInfo newInfo = new passiveInfo(passive_Id, status_Type, status_Arg, passive_name, image_Res);
			dataInfo.Add(newInfo);
			datas.Add(key, newInfo);
			return true;
        }
        
        public void Initialize()
        {
			var newDatas = new Dictionary<System.Int16, passiveInfo>();
			foreach (var data in dataInfo)
			{
				System.Int16 key = data.passive_Id;
				if (newDatas.ContainsKey(key))
					throw new InvalidOperationException("Duplicate primary key in table 'passive': " + key);
				newDatas.Add(key, data);
			}
			datas = newDatas;
        }
        
        public passiveInfo Get(short passive_Id)
        {
			passiveInfo value = null;
			if (datas.TryGetValue(passive_Id, out value))
				return value;
			return null;
        }
    }
}
