//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignTable
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using ProtoBuf;
    
    
    [ProtoContract()]
    public class projectileInfo
    {
        
        [ProtoMember(1)]
        public int projectile_Id;
        
        [ProtoMember(2)]
        public string projectile_path;
        
        [ProtoMember(3)]
        public short projectile_speed;
        
        public projectileInfo()
        {
        }
        
        public projectileInfo(int projectile_Id, string projectile_path, short projectile_speed)
        {
			this.projectile_Id = projectile_Id;
			this.projectile_path = projectile_path;
			this.projectile_speed = projectile_speed;
        }
    }
    
    [ProtoContract()]
    public class projectileInfos
    {
        
        [ProtoMember(1)]
        public List<projectileInfo> dataInfo = new List<projectileInfo>();
        
        public Dictionary<ArraySegment<byte>, projectileInfo> datas = new Dictionary<ArraySegment<byte>, projectileInfo>(new DataComparer());
        
        public bool Insert(int projectile_Id, string projectile_path, short projectile_speed)
        {
			ArraySegment<byte> key = GetIdRule(projectile_Id);
			if (datas.ContainsKey(key))
				return false;
			projectileInfo newInfo = new projectileInfo(projectile_Id, projectile_path, projectile_speed);
			dataInfo.Add(newInfo);
			datas.Add(key, newInfo);
			return true;
        }
        
        public void Initialize()
        {
			foreach (var data in dataInfo)
			{
				ArraySegment<byte> bytes = GetIdRule(data.projectile_Id);
				if (datas.ContainsKey(bytes))
					continue;
				datas.Add(bytes, data);
			}
        }
        
        public projectileInfo Get(int projectile_Id)
        {
			projectileInfo value = null;
			if (datas.TryGetValue(GetIdRule(projectile_Id), out value))
				return value;
			return null;
        }
        
        public System.ArraySegment<byte> GetIdRule(int projectile_Id)
        {
			ushort total = 0;
			ushort count = 0;
			total += sizeof(int);
			if (total == 0)
				return default(System.ArraySegment<byte>);
			byte[] bytes = new byte[total];
			Array.Copy(BitConverter.GetBytes(projectile_Id), 0, bytes, count, sizeof(int));
			count += sizeof(int);
			return new System.ArraySegment<byte>(bytes);
        }
    }
}
