//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignTable
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using ProtoBuf;
    
    
    [ProtoContract()]
    public class projectileInfo
    {
        
        [ProtoMember(1)]
        public int projectile_Id;
        
        [ProtoMember(2)]
        public string projectile_path;
        
        [ProtoMember(3)]
        public short projectile_speed;
        
        public projectileInfo()
        {
        }
        
        public projectileInfo(int projectile_Id, string projectile_path, short projectile_speed)
        {
			this.projectile_Id = projectile_Id;
			this.projectile_path = projectile_path;
			this.projectile_speed = projectile_speed;
        }
    }
    
    [ProtoContract()]
    public class projectileInfos
    {
        
        [ProtoMember(1)]
        public List<projectileInfo> dataInfo = new List<projectileInfo>();
        
        public Dictionary<System.Int32, projectileInfo> datas = new Dictionary<System.Int32, projectileInfo>();
        
        public bool Insert(int projectile_Id, string projectile_path, short projectile_speed)
        {
			System.Int32 key = projectile_Id;
			if (datas.ContainsKey(key))
				return false;
			projectileInfo newInfo = new projectileInfo(projectile_Id, projectile_path, projectile_speed);
			dataInfo.Add(newInfo);
			datas.Add(key, newInfo);
			return true;
        }
        
        public void Initialize()
        {
			var newDatas = new Dictionary<System.Int32, projectileInfo>();
			foreach (var data in dataInfo)
			{
				System.Int32 key = data.projectile_Id;
				if (newDatas.ContainsKey(key))
					throw new InvalidOperationException("Duplicate primary key in table 'projectile': " + key);
				newDatas.Add(key, data);
			}
			datas = newDatas;
        }
        
        public projectileInfo Get(int projectile_Id)
        {
			projectileInfo value = null;
			if (datas.TryGetValue(projectile_Id, out value))
				return value;
			return null;
        }
    }
}
