//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignTable
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using ProtoBuf;
    
    
    [ProtoContract()]
    public class SceneDataInfo
    {
        
        [ProtoMember(1)]
        public string SceneName;
        
        [ProtoMember(2)]
        public string Path;
        
        public SceneDataInfo()
        {
        }
        
        public SceneDataInfo(string SceneName, string Path)
        {
			this.SceneName = SceneName;
			this.Path = Path;
        }
    }
    
    [ProtoContract()]
    public class SceneDataInfos
    {
        
        [ProtoMember(1)]
        public List<SceneDataInfo> dataInfo = new List<SceneDataInfo>();
        
        public Dictionary<System.String, SceneDataInfo> datas = new Dictionary<System.String, SceneDataInfo>();
        
        public bool Insert(string SceneName, string Path)
        {
			if (SceneName == null)
				throw new ArgumentNullException("SceneName", "Primary key in table 'SceneData' cannot be null.");
			System.String key = SceneName;
			if (datas.ContainsKey(key))
				return false;
			SceneDataInfo newInfo = new SceneDataInfo(SceneName, Path);
			dataInfo.Add(newInfo);
			datas.Add(key, newInfo);
			return true;
        }
        
        public void Initialize()
        {
			var newDatas = new Dictionary<System.String, SceneDataInfo>();
			foreach (var data in dataInfo)
			{
				if (data.SceneName == null)
					throw new InvalidOperationException("Primary key 'SceneName' in table 'SceneData' cannot be null.");
				System.String key = data.SceneName;
				if (newDatas.ContainsKey(key))
					throw new InvalidOperationException("Duplicate primary key in table 'SceneData': " + key);
				newDatas.Add(key, data);
			}
			datas = newDatas;
        }
        
        public SceneDataInfo Get(string SceneName)
        {
			if (SceneName == null)
				throw new ArgumentNullException("SceneName", "Primary key in table 'SceneData' cannot be null.");
			SceneDataInfo value = null;
			if (datas.TryGetValue(SceneName, out value))
				return value;
			return null;
        }
    }
}
