//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignTable
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using ProtoBuf;
    
    
    [ProtoContract()]
    public class SceneDataInfo
    {
        
        [ProtoMember(1)]
        public string SceneName;
        
        [ProtoMember(2)]
        public string Path;
        
        public SceneDataInfo()
        {
        }
        
        public SceneDataInfo(string SceneName, string Path)
        {
			this.SceneName = SceneName;
			this.Path = Path;
        }
    }
    
    [ProtoContract()]
    public class SceneDataInfos
    {
        
        [ProtoMember(1)]
        public List<SceneDataInfo> dataInfo = new List<SceneDataInfo>();
        
        public Dictionary<ArraySegment<byte>, SceneDataInfo> datas = new Dictionary<ArraySegment<byte>, SceneDataInfo>(new DataComparer());
        
        public bool Insert(string SceneName, string Path)
        {
			ArraySegment<byte> key = GetIdRule(SceneName);
			if (datas.ContainsKey(key))
				return false;
			SceneDataInfo newInfo = new SceneDataInfo(SceneName, Path);
			dataInfo.Add(newInfo);
			datas.Add(key, newInfo);
			return true;
        }
        
        public void Initialize()
        {
			foreach (var data in dataInfo)
			{
				ArraySegment<byte> bytes = GetIdRule(data.SceneName);
				if (datas.ContainsKey(bytes))
					continue;
				datas.Add(bytes, data);
			}
        }
        
        public SceneDataInfo Get(string SceneName)
        {
			SceneDataInfo value = null;
			if (datas.TryGetValue(GetIdRule(SceneName), out value))
				return value;
			return null;
        }
        
        public System.ArraySegment<byte> GetIdRule(string SceneName)
        {
			ushort total = 0;
			ushort count = 0;
			total += (ushort)System.Text.Encoding.UTF8.GetByteCount(SceneName);
			if (total == 0)
				return default(System.ArraySegment<byte>);
			byte[] bytes = new byte[total];
			byte[] stringBytes;
			stringBytes = System.Text.Encoding.UTF8.GetBytes(SceneName);
			Array.Copy(stringBytes, 0, bytes, count, stringBytes.Length);
			count += (ushort)stringBytes.Length;
			return new System.ArraySegment<byte>(bytes);
        }
    }
}
