//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignTable
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using ProtoBuf;
    
    
    [ProtoContract()]
    public class skill_effectInfo
    {
        
        [ProtoMember(1)]
        public int effect_Id;
        
        [ProtoMember(2)]
        public string effect_path;
        
        public skill_effectInfo()
        {
        }
        
        public skill_effectInfo(int effect_Id, string effect_path)
        {
			this.effect_Id = effect_Id;
			this.effect_path = effect_path;
        }
    }
    
    [ProtoContract()]
    public class skill_effectInfos
    {
        
        [ProtoMember(1)]
        public List<skill_effectInfo> dataInfo = new List<skill_effectInfo>();
        
        public Dictionary<System.Int32, skill_effectInfo> datas = new Dictionary<System.Int32, skill_effectInfo>();
        
        public bool Insert(int effect_Id, string effect_path)
        {
			System.Int32 key = effect_Id;
			if (datas.ContainsKey(key))
				return false;
			skill_effectInfo newInfo = new skill_effectInfo(effect_Id, effect_path);
			dataInfo.Add(newInfo);
			datas.Add(key, newInfo);
			return true;
        }
        
        public void Initialize()
        {
			var newDatas = new Dictionary<System.Int32, skill_effectInfo>();
			foreach (var data in dataInfo)
			{
				System.Int32 key = data.effect_Id;
				if (newDatas.ContainsKey(key))
					throw new InvalidOperationException("Duplicate primary key in table 'skill_effect': " + key);
				newDatas.Add(key, data);
			}
			datas = newDatas;
        }
        
        public skill_effectInfo Get(int effect_Id)
        {
			skill_effectInfo value = null;
			if (datas.TryGetValue(effect_Id, out value))
				return value;
			return null;
        }
    }
}
