//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignTable
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using ProtoBuf;
    
    
    [ProtoContract()]
    public class skillInfo
    {
        
        [ProtoMember(1)]
        public int unit_Class;
        
        [ProtoMember(2)]
        public int unit_type;
        
        [ProtoMember(3)]
        public int skill_Id;
        
        [ProtoMember(4)]
        public float skill_coolTime;
        
        [ProtoMember(5)]
        public float skill_range;
        
        [ProtoMember(6)]
        public float skill_radius;
        
        [ProtoMember(7)]
        public float skill_scale;
        
        [ProtoMember(8)]
        public int skill_buffId;
        
        public buffInfo skill_buffId_ref;
        
        [ProtoMember(9)]
        public sbyte skill_type;
        
        [ProtoMember(10)]
        public sbyte skill_attackType;
        
        [ProtoMember(11)]
        public bool skill_contoroll;
        
        [ProtoMember(12)]
        public bool skill_dash;
        
        [ProtoMember(13)]
        public float skill_dashSpeed;
        
        [ProtoMember(14)]
        public bool skill_judgeAni;
        
        [ProtoMember(15)]
        public float skill_judgeTime;
        
        [ProtoMember(16)]
        public int effect_Id;
        
        public skill_effectInfo effect_Id_ref;
        
        [ProtoMember(17)]
        public int hit_effect_Id;
        
        [ProtoMember(18)]
        public string image_Res;
        
        [ProtoMember(19)]
        public string sound_Res;
        
        [ProtoMember(20)]
        public string hitSound_Res;
        
        [ProtoMember(21)]
        public bool sound_Ani;
        
        [ProtoMember(22)]
        public int projectile_Id;
        
        public projectileInfo projectile_Id_ref;
        
        public skillInfo()
        {
        }
        
        public skillInfo(
                    int unit_Class, 
                    int unit_type, 
                    int skill_Id, 
                    float skill_coolTime, 
                    float skill_range, 
                    float skill_radius, 
                    float skill_scale, 
                    int skill_buffId, 
                    sbyte skill_type, 
                    sbyte skill_attackType, 
                    bool skill_contoroll, 
                    bool skill_dash, 
                    float skill_dashSpeed, 
                    bool skill_judgeAni, 
                    float skill_judgeTime, 
                    int effect_Id, 
                    int hit_effect_Id, 
                    string image_Res, 
                    string sound_Res, 
                    string hitSound_Res, 
                    bool sound_Ani, 
                    int projectile_Id)
        {
			this.unit_Class = unit_Class;
			this.unit_type = unit_type;
			this.skill_Id = skill_Id;
			this.skill_coolTime = skill_coolTime;
			this.skill_range = skill_range;
			this.skill_radius = skill_radius;
			this.skill_scale = skill_scale;
			this.skill_buffId = skill_buffId;
			this.skill_type = skill_type;
			this.skill_attackType = skill_attackType;
			this.skill_contoroll = skill_contoroll;
			this.skill_dash = skill_dash;
			this.skill_dashSpeed = skill_dashSpeed;
			this.skill_judgeAni = skill_judgeAni;
			this.skill_judgeTime = skill_judgeTime;
			this.effect_Id = effect_Id;
			this.hit_effect_Id = hit_effect_Id;
			this.image_Res = image_Res;
			this.sound_Res = sound_Res;
			this.hitSound_Res = hitSound_Res;
			this.sound_Ani = sound_Ani;
			this.projectile_Id = projectile_Id;
        }
    }
    
    [ProtoContract()]
    public class skillInfos
    {
        
        [ProtoMember(1)]
        public List<skillInfo> dataInfo = new List<skillInfo>();
        
        public Dictionary<System.Int32, skillInfo> datas = new Dictionary<System.Int32, skillInfo>();
        
        public Dictionary<System.Int32, List<skillInfo>> listData = new Dictionary<System.Int32, List<skillInfo>>();
        
        public bool Insert(
                    int unit_Class, 
                    int unit_type, 
                    int skill_Id, 
                    float skill_coolTime, 
                    float skill_range, 
                    float skill_radius, 
                    float skill_scale, 
                    int skill_buffId, 
                    sbyte skill_type, 
                    sbyte skill_attackType, 
                    bool skill_contoroll, 
                    bool skill_dash, 
                    float skill_dashSpeed, 
                    bool skill_judgeAni, 
                    float skill_judgeTime, 
                    int effect_Id, 
                    int hit_effect_Id, 
                    string image_Res, 
                    string sound_Res, 
                    string hitSound_Res, 
                    bool sound_Ani, 
                    int projectile_Id)
        {
			System.Int32 key = skill_Id;
			if (datas.ContainsKey(key))
				return false;
			skillInfo newInfo = new skillInfo(unit_Class, unit_type, skill_Id, skill_coolTime, skill_range, skill_radius, skill_scale, skill_buffId, skill_type, skill_attackType, skill_contoroll, skill_dash, skill_dashSpeed, skill_judgeAni, skill_judgeTime, effect_Id, hit_effect_Id, image_Res, sound_Res, hitSound_Res, sound_Ani, projectile_Id);
			dataInfo.Add(newInfo);
			datas.Add(key, newInfo);
			System.Int32 listKey = skill_Id;
			List<skillInfo> listValues = null;
			if (!listData.TryGetValue(listKey, out listValues))
			{
				listValues = new List<skillInfo>();
				listData.Add(listKey, listValues);
			}
			listValues.Add(newInfo);
			return true;
        }
        
        public void Initialize()
        {
			var newDatas = new Dictionary<System.Int32, skillInfo>();
			var newListData = new Dictionary<System.Int32, List<skillInfo>>();
			foreach (var data in dataInfo)
			{
				System.Int32 key = data.skill_Id;
				if (newDatas.ContainsKey(key))
					throw new InvalidOperationException("Duplicate primary key in table 'skill': " + key);
				newDatas.Add(key, data);
				System.Int32 listKey = data.skill_Id;
				List<skillInfo> listValues = null;
				if (!newListData.TryGetValue(listKey, out listValues))
				{
					listValues = new List<skillInfo>();
					newListData.Add(listKey, listValues);
				}
				listValues.Add(data);
			}
			datas = newDatas;
			listData = newListData;
        }
        
        public skillInfo Get(int skill_Id)
        {
			skillInfo value = null;
			if (datas.TryGetValue(skill_Id, out value))
				return value;
			return null;
        }
        
        public List<skillInfo> GetListById(int skill_Id)
        {
			List<skillInfo> value = null;
			if (listData.TryGetValue(skill_Id, out value))
				return value;
			return null;
        }
        
        public void SetupRef_skill_buffId(buffInfos infos)
        {
			foreach (skillInfo data in dataInfo)
			{
				if (data.skill_buffId != -1)
				{
					data.skill_buffId_ref = infos.Get(data.skill_buffId);
					if (data.skill_buffId_ref == null)
						throw new InvalidOperationException("테이블 'skill' 의 'skill_buffId' 참조를 'buff' 에서 찾을 수 없습니다: " + data.skill_buffId);
				}
			}
        }
        
        public void SetupRef_effect_Id(skill_effectInfos infos)
        {
			foreach (skillInfo data in dataInfo)
			{
				if (data.effect_Id != -1)
				{
					data.effect_Id_ref = infos.Get(data.effect_Id);
					if (data.effect_Id_ref == null)
						throw new InvalidOperationException("테이블 'skill' 의 'effect_Id' 참조를 'skill_effect' 에서 찾을 수 없습니다: " + data.effect_Id);
				}
			}
        }
        
        public void SetupRef_projectile_Id(projectileInfos infos)
        {
			foreach (skillInfo data in dataInfo)
			{
				if (data.projectile_Id != -1)
				{
					data.projectile_Id_ref = infos.Get(data.projectile_Id);
					if (data.projectile_Id_ref == null)
						throw new InvalidOperationException("테이블 'skill' 의 'projectile_Id' 참조를 'projectile' 에서 찾을 수 없습니다: " + data.projectile_Id);
				}
			}
        }
    }
}
