//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignTable
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using ProtoBuf;
    
    
    [ProtoContract()]
    public class user_characterInfo
    {
        
        [ProtoMember(1)]
        public int char_Id;
        
        [ProtoMember(2)]
        public sbyte char_classId;
        
        [ProtoMember(3)]
        public sbyte char_gender;
        
        [ProtoMember(4)]
        public short char_atk;
        
        [ProtoMember(5)]
        public short char_def;
        
        [ProtoMember(6)]
        public float char_moveSpeed;
        
        [ProtoMember(7)]
        public string char_prefab;
        
        public user_characterInfo()
        {
        }
        
        public user_characterInfo(int char_Id, sbyte char_classId, sbyte char_gender, short char_atk, short char_def, float char_moveSpeed, string char_prefab)
        {
			this.char_Id = char_Id;
			this.char_classId = char_classId;
			this.char_gender = char_gender;
			this.char_atk = char_atk;
			this.char_def = char_def;
			this.char_moveSpeed = char_moveSpeed;
			this.char_prefab = char_prefab;
        }
    }
    
    [ProtoContract()]
    public class user_characterInfos
    {
        
        [ProtoMember(1)]
        public List<user_characterInfo> dataInfo = new List<user_characterInfo>();
        
        public Dictionary<System.Int32, user_characterInfo> datas = new Dictionary<System.Int32, user_characterInfo>();
        
        public bool Insert(int char_Id, sbyte char_classId, sbyte char_gender, short char_atk, short char_def, float char_moveSpeed, string char_prefab)
        {
			System.Int32 key = char_Id;
			if (datas.ContainsKey(key))
				return false;
			user_characterInfo newInfo = new user_characterInfo(char_Id, char_classId, char_gender, char_atk, char_def, char_moveSpeed, char_prefab);
			dataInfo.Add(newInfo);
			datas.Add(key, newInfo);
			return true;
        }
        
        public void Initialize()
        {
			var newDatas = new Dictionary<System.Int32, user_characterInfo>();
			foreach (var data in dataInfo)
			{
				System.Int32 key = data.char_Id;
				if (newDatas.ContainsKey(key))
					throw new InvalidOperationException("Duplicate primary key in table 'user_character': " + key);
				newDatas.Add(key, data);
			}
			datas = newDatas;
        }
        
        public user_characterInfo Get(int char_Id)
        {
			user_characterInfo value = null;
			if (datas.TryGetValue(char_Id, out value))
				return value;
			return null;
        }
    }
}
