//------------------------------------------------------------------------------
// <auto-generated>
//     TableGen 이 생성한 파일입니다. 직접 수정하지 마세요.
//     원본: enum.xlsx
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignEnum
{
    /// <summary>속성 ID</summary>
    /// <remarks>GROUP_ID = 1001</remarks>
    public enum AttributeId
    {
        /// <summary>Atk</summary>
        Atk = 0,

        /// <summary>Def</summary>
        Def = 1,
    }

    /// <summary>시간 타입</summary>
    /// <remarks>GROUP_ID = 1002</remarks>
    public enum TimeType
    {
        /// <summary>All</summary>
        All = 0,

        /// <summary>Morning</summary>
        Morning = 1,

        /// <summary>Noon</summary>
        Noon = 2,

        /// <summary>Night</summary>
        Night = 3,

        /// <summary>Midnight</summary>
        Midnight = 4,
    }

    /// <summary>유닛 타입</summary>
    /// <remarks>GROUP_ID = 1003</remarks>
    public enum UnitType
    {
        /// <summary>Monster</summary>
        Monster = 0,

        /// <summary>Character</summary>
        Character = 1,
    }

    /// <summary>클래스 타입</summary>
    /// <remarks>GROUP_ID = 1004</remarks>
    public enum ClassType
    {
        /// <summary>Monk</summary>
        Monk = 0,
    }

    /// <summary>버프 타입</summary>
    /// <remarks>GROUP_ID = 1005</remarks>
    public enum BuffType
    {
        /// <summary>공격력 증가</summary>
        AddATK = 0,

        /// <summary>방어력 증가</summary>
        AddDEF = 1,

        /// <summary>공격력 감소</summary>
        LowATK = 2,

        /// <summary>방어력 감소</summary>
        LowDEF = 3,

        /// <summary>스턴</summary>
        Strun = 4,

        /// <summary>도트</summary>
        Dot = 5,
    }

    /// <summary>스킬 타입</summary>
    /// <remarks>GROUP_ID = 1006</remarks>
    public enum SkillType
    {
        /// <summary>일반 공격</summary>
        Normal = 0,

        /// <summary>근접 공격</summary>
        Melee = 1,

        /// <summary>범위 공격</summary>
        Range = 2,
    }

    /// <summary>성별</summary>
    /// <remarks>GROUP_ID = 1007</remarks>
    public enum Gender
    {
        /// <summary>남자</summary>
        Male = 0,

        /// <summary>여자</summary>
        Female = 1,
    }

    /// <summary>스킬 ID</summary>
    /// <remarks>GROUP_ID = 1008</remarks>
    public enum SkillID
    {
        /// <summary>일반 공격 1</summary>
        Attack1 = 101,

        /// <summary>스킬 공격 1</summary>
        Skill1 = 201,

        /// <summary>스킬 공격 2</summary>
        Skill2 = 202,

        /// <summary>스킬 공격 3</summary>
        Skill3 = 203,

        /// <summary>스킬 공격 4</summary>
        Skill4 = 204,
    }

    /// <summary>스킬 공격 타입</summary>
    /// <remarks>GROUP_ID = 1009</remarks>
    public enum SkillAttackType
    {
        /// <summary>원형</summary>
        Circle = 0,

        /// <summary>직선</summary>
        Straight = 1,
    }

    /// <summary>몬스터 타입</summary>
    /// <remarks>GROUP_ID = 1010</remarks>
    public enum MonsterType
    {
        /// <summary>필드 일반</summary>
        FieldNormal = 0,

        /// <summary>던전 일반</summary>
        DungeonNormal = 1,

        /// <summary>필드 보스</summary>
        FieldBoss = 2,

        /// <summary>던전 보스</summary>
        DungeonBoss = 3,
    }

    /// <summary>필드 타입</summary>
    /// <remarks>GROUP_ID = 1011</remarks>
    public enum FieldType
    {
        /// <summary>필드</summary>
        Field = 0,

        /// <summary>던전</summary>
        Dungeon = 1,
    }

    /// <summary>퀘스트 타입</summary>
    /// <remarks>GROUP_ID = 1012</remarks>
    public enum QuestType
    {
        /// <summary>몬스터 사냥</summary>
        MonsterHunt = 0,
    }

    /// <summary>패시브 타입</summary>
    /// <remarks>GROUP_ID = 1013</remarks>
    public enum PassiveType
    {
        /// <summary>공격력</summary>
        ATK = 0,

        /// <summary>방어력</summary>
        DEF = 1,

        /// <summary>체력</summary>
        HP = 2,
    }

    /// <summary>패시브 타입</summary>
    /// <remarks>GROUP_ID = 1014</remarks>
    public enum SoundList
    {
        /// <summary>None</summary>
        None = 0,
    }

    /// <summary>아틀라스 타입</summary>
    /// <remarks>GROUP_ID = 1015</remarks>
    public enum AtlasType
    {
        /// <summary>공용</summary>
        Common = 0,
    }
}
