//------------------------------------------------------------------------------
// <auto-generated>
//     �� �ڵ�� ������ ����Ͽ� �����Ǿ����ϴ�.
//     ��Ÿ�� ����:4.0.30319.42000
//
//     ���� ������ �����ϸ� �߸��� ������ �߻��� �� ������, �ڵ带 �ٽ� �����ϸ�
//     �̷��� ���� ������ �սǵ˴ϴ�.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignEnum
{
    
    
    // ID : 1001
    public enum AttributeId
    {
        
        Atk = 0,
        
        Def = 1,
    }
    
    // ID : 1002
    public enum TimeType
    {
        
        All = 0,
        
        Morning = 1,
        
        Noon = 2,
        
        Night = 3,
        
        Midnight = 4,
    }
    
    // ID : 1003
    public enum UnitType
    {
        
        Monster = 0,
        
        Character = 1,
    }
    
    // ID : 1004
    public enum ClassType
    {
        
        Monk = 0,
    }
    
    // ID : 1005
    public enum BuffType
    {
        
        AddATK = 0,
        
        AddDEF = 1,
        
        LowATK = 2,
        
        LowDEF = 3,
        
        Strun = 4,
        
        Dot = 5,
    }
    
    // ID : 1006
    public enum SkillType
    {
        
        Normal = 0,
        
        Melee = 1,
        
        Range = 2,
    }
    
    // ID : 1007
    public enum Gender
    {
        
        Male = 0,
        
        Female = 1,
    }
    
    // ID : 1008
    public enum SkillID
    {
        
        Attack1 = 101,
        
        Skill1 = 201,
        
        Skill2 = 202,
        
        Skill3 = 203,
        
        Skill4 = 204,
    }
    
    // ID : 1009
    public enum SkillAttackType
    {
        
        Circle = 0,
        
        Straight = 1,
    }
    
    // ID : 1010
    public enum MonsterType
    {
        
        FieldNormal = 0,
        
        DungeonNormal = 1,
        
        FieldBoss = 2,
        
        DungeonBoss = 3,
    }
    
    // ID : 1011
    public enum FieldType
    {
        
        Field = 0,
        
        Dungeon = 1,
    }
    
    // ID : 1012
    public enum QuestType
    {
        
        MonsterHunt = 0,
    }
    
    // ID : 1013
    public enum PassiveType
    {
        
        ATK = 0,
        
        DEF = 1,
        
        HP = 2,
    }
    
    // ID : 1014
    public enum SoundList
    {
        
        None = 0,
    }
    
    // ID : 1015
    public enum AtlasType
    {
        
        Common = 0,
    }
}
