using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml;
using DesignGenerator.Core;
using DesignGenerator.Util;

namespace DesignGenerator.Enum
{
    public static class EnumCodeWriter
    {
        public static string Write(IList<EnumGroup> groups, string namespaceName, string sourceName)
        {
            StringBuilder sb = new StringBuilder(16 * 1024);

            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     TableGen 이 생성한 파일입니다. 직접 수정하지 마세요.");
            sb.AppendLine("//     원본: " + sourceName);
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine("namespace " + namespaceName);
            sb.AppendLine("{");

            var ordered = groups.OrderBy(g => g.GroupId).ToList();

            for (int gi = 0; gi < ordered.Count; ++gi)
            {
                var g = ordered[gi];
                if (gi > 0)
                    sb.AppendLine();

                string comment = XmlDocText.Flatten(g.Comment);
                if (!string.IsNullOrEmpty(comment))
                    sb.AppendLine("    /// <summary>" + XmlDocText.Escape(comment) + "</summary>");

                sb.AppendLine("    /// <remarks>GROUP_ID = " + g.GroupId.ToString(CultureInfo.InvariantCulture) + "</remarks>");

                if (g.IsFlags)
                    sb.AppendLine("    [System.Flags]");

                sb.Append("    public enum ").Append(g.TypeName);
                if (g.BaseType != "int")
                    sb.Append(" : ").Append(g.BaseType);

                sb.AppendLine();
                sb.AppendLine("    {");

                // 값 순으로 정렬해 읽기 좋게.
                var members = g.Members.OrderBy(m => m.Value).ToList();

                for (int mi = 0; mi < members.Count; mi++)
                {
                    var m = members[mi];
                    string mc = XmlDocText.Flatten(m.Comment);

                    if (!string.IsNullOrEmpty(mc))
                    {
                        if (mi > 0)
                            sb.AppendLine();
                        sb.AppendLine("        /// <summary>" + XmlDocText.Escape(mc) + "</summary>");
                    }

                    sb.Append("        ").Append(m.Name).Append(" = ");

                    if (g.IsFlags && m.Value != 0)
                        sb.Append("0x").Append(m.Value.ToString("X", CultureInfo.InvariantCulture));
                    else
                        sb.Append(m.Value.ToString(CultureInfo.InvariantCulture));

                    sb.AppendLine(",");
                }

                sb.AppendLine("    }");
            }

            sb.AppendLine("}");
            return sb.ToString();
        }
    }

    public sealed class EnumGenerateOptions
    {
        public string DataRoot;
        public string OutputRoot;
        public string NamespaceName = "DesignEnum";
        public bool ExportXmlFromExcel = true;
        public bool TreatWarningsAsErrors = false;

        public Action<string, string> XmlExporter;
    }

    public sealed class EnumGenerateResult
    {
        public DiagnosticBag Diagnostics = new DiagnosticBag();
        public List<EnumGroup> Groups = new List<EnumGroup>();
        public string OutputFile;
        public bool FileWritten;
        public bool Succeeded;
    }

    public static class EnumPipeline
    {
        public static EnumGenerateResult Run(EnumGenerateOptions options)
        {
            var result = new EnumGenerateResult();
            var diag = result.Diagnostics;

            string dataRoot = (options.DataRoot ?? string.Empty).Trim();
            string xlsxPath = Path.Combine(dataRoot, "Enum", "enum.xlsx");
            string xmlPath = Path.Combine(dataRoot, "Enum", "enum.xml");
            string outDir = Path.Combine((options.OutputRoot ?? string.Empty).Trim(), "Automation", "Enum");
            string outFile = Path.Combine(outDir, "DesignEnum.cs");
            result.OutputFile = outFile;

            //1.엑셀 -> XML
            if (options.ExportXmlFromExcel)
            {
                if (!File.Exists(xlsxPath))
                {
                    diag.Error("TG0001", SourceLocation.InFile(xlsxPath), "enum.xlsx 를 찾을 수 없습니다.");
                    return Finish(result, options);
                }

                //증분: xlsx 가 xml 보다 새로울 때만 엑셀을 띄운다.
                bool needExport = !File.Exists(xmlPath) || File.GetLastWriteTimeUtc(xlsxPath) > File.GetLastWriteTimeUtc(xmlPath);

                if (needExport)
                {
                    try
                    {
                        Directory.CreateDirectory(Path.GetDirectoryName(xmlPath));

                        if (options.XmlExporter != null)
                            options.XmlExporter(xlsxPath, xmlPath);
                        else
                            ExcelUtils.ExportXml(xlsxPath, xmlPath);
                    }
                    catch (Exception e)
                    {
                        diag.Error("TG0003", SourceLocation.InFile(xlsxPath),
                            "엑셀에서 XML 을 내보내지 못했습니다: " + e.Message,
                            "엑셀에서 파일이 열려 있지 않은지, XmlMap 이 설정돼 있는지 확인하세요.");
                        return Finish(result, options);
                    }
                }
            }

            //2.읽기
            var source = new XmlEnumRecordSource(xmlPath);
            result.Groups = EnumReader.Read(source, diag);

            //3.검증
            EnumValidator.Validate(result.Groups, diag);

            //오류가 있으면 생성하지 않는다. 깨진 .cs를 Unity에 떨어뜨리는 것보다.
            //아무것도 안 하는 편이 더 좋음
            if (diag.HasError)
                return Finish(result, options);

            //4.생성
            string code = EnumCodeWriter.Write(result.Groups, options.NamespaceName, Path.GetFileName(xlsxPath));
            result.FileWritten = GeneratedFileWriter.WriteIfChanged(outFile, code);

            return Finish(result, options);
        }

        private static EnumGenerateResult Finish(EnumGenerateResult r, EnumGenerateOptions o)
        {
            r.Succeeded = !r.Diagnostics.HasError
                          && !(o.TreatWarningsAsErrors && r.Diagnostics.WarningCount > 0);
            return r;
        }
    }
}
