# DesignTool 설정. 직접 고쳐도 된다.
GeneratorPath=D:\Project\ProjectT\DesignTable\Gen\DesignGenerator.exe
DataPath=D:\Project\ProjectT\DesignTable\Data
OutputPath=D:\Project\ProjectT\Client\Assets
Full=False
WarnAsError=False
Merge=False
