ARG REGISTRY_SERVER
FROM ${REGISTRY_SERVER}/ubuntu20:latest

#Install python-tools
RUN apt -y -q update && apt -y -q upgrade && \
apt-get -yq install curl build-essential zlib1g-dev libncurses5-dev libcurl4-openssl-dev libgdbm-dev libnss3-dev libpq-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev default-libmysqlclient-dev && \
mkdir -p /usr/local/src/python_3_7_9_install && \ 
wget -P /usr/local/src/python_3_7_9_install/ https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz && \
cd /usr/local/src/python_3_7_9_install && \
tar xzvf /usr/local/src/python_3_7_9_install/Python-3.7.9.tgz && \
cd Python-3.7.9 && \
./configure --enable-optimizations && \
make altinstall && make install

#Install pip
RUN curl https://bootstrap.pypa.io/get-pip.py | python3 && \
ln -s /usr/local/bin/pip3 /usr/bin/pip3 && \
ln -s /usr/local/bin/pip3 /usr/bin/pip

#Install requirements
ARG DJANGO_SERVER_ROOT
ARG DJANGO_SERVER_ROOT ${DJANGO_SERVER_ROOT}
RUN mkdir -p $DJANGO_SERVER_ROOT
WORKDIR ${DJANGO_SERVER_ROOT}
COPY ./docker_configs/django3/requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

COPY ./docker_entrypoints/docker-entrypoint-django3.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

COPY ./docker_build_info.txt /tmp/
COPY ./docker_configs/django3/urls.py /tmp/
EXPOSE 8000
