version: '3'

services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        volumes:
            - D:/ProjectT/Tools/Docker/Test/docker.sock:/var/run/docker.sock
            - D:/ProjectT/Tools/Docker/Test:/var/jenkins_home
        ports:
            - "8081:8080"
        privileged: true
        user: root
        build:
            context: ../
            dockerfile: ./dockerfiles/Jenkins/dockerfile-jenkins